mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2024-07-10"
  bei_an: 苏ICP备2024135369号-1
  title: 博书-Booke
  qq_image: http://127.0.0.1:8080/uploads/file/qq二维码.jpg
  version: "7.0"
  email: 2215943316@qq.com
  wechat_image: http://127.0.0.1:8080/uploads/file/微信二维码.jpg
  name: 博书-booke
  job: 全栈开发
  addr: 江苏镇江
  slogan: 博书
  slogan_en: BOOKE
  web: https://www.booke.cloud/
  bilibili_url: 暂时无
  gitee_url: 暂时无
  github_url: https://github.com/wcnnnd11
upload:
  size: 5
  path: uploads/file/
qq:
  app_id: "101974593"
  key: kQsBICtPgiV3QZYJ
  redirect: ""
qi_niu:
  enable: false
  access_key: zvKeZtDSUe5I_DtXF7yXobhV4JSiPSg5SjSqy1-s
  secret_key: '******'
  bucket: lij1ang
  cdn: http://sggm2o2yh.hd-bkt.clouddn.com/
  zone: z0
  prefix: gvb
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 2215943316@qq.com
  password: "123456"
  default_from_email: 江川之息
  use_ssl: true
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
redis:
  ip: 127.0.0.1
  port: 6379
  password: redis
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
