mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 5
  path: uploads/file/
site_info:
  created_at: "2024-07-10"
  bei_an: 苏ICP备2024135369号-1
  title: 璃江的个人博客
  qq_image: 暂时无
  version: "7.0"
  email: 2215943316@qq.com
  wechat_image: 暂时无
  name: 博书-booke
  job: 全栈开发
  addr: 江苏镇江
  slogan: 博书
  slogan_en: BOOKE
  web: https://www.booke.cloud/
  bilibili_url: 暂时无
  gitee_url: 暂时无
  github_url: 暂时无
qq:
  app_id: 101974593
  key: kQsBICtPgiV3QZYJ
  redirect:
qi_niu:
  enable: true
  access_key: zvKeZtDSUe5I_DtXF7yXobhV4JSiPSg5SjSqy1-s
  secret_key: T_YOBjVIme0iXqrvZzjhE3NqFBwGHxqzT3aVdyMd
  bucket: lij1ang
  cdn: http://sggm2o2yh.hd-bkt.clouddn.com/
  zone: z0
  prefix: "gvb"
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 2215943316@qq.com
  password: vplbvofgihnidijj
  default_from_email: 江川之息
  use_ssl: true
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
redis:
  ip: 127.0.0.1
  port: 6379
  password: "redis"
  pool_size: 100
es:
  host: "http://127.0.0.1"
  port: 9200
  user:
  password: